### ISSUE TITLE
Test issue2

### ISSUE THREAD

**Issue by hm23** [cap-js/graphql#164]

**Comment by daogrady** [comment]
@hm23 I just stumbled upon your workflow to automagically label new issues and wanted to point out GH's issue templates, which allow you to define different classes of issues and to give each class default labels: https://github.com/cap-js/cds-typer/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml 🙂

**Comment by hm23** [comment]
@daogrady, thanks for suggesting - would be a good alternative indeed. We (node runtime team) anyhow have to clarify how we organise and monitor the various issue channels. In this context we will probably also revisit how we use labels and how this can be automated...
